Jeyner Arango

Oscar Méndez 20402

# Lista 03

In [4]:
import numpy as np
import pandas as pd

## Ejercicio 3

Primero generamos dos matrices dispersas de forma aleatoria

In [5]:
m = 3500
n = 2800

a = np.random.randint(-100, 100, size=m*n) * np.random.choice([0, 1], p=[0.95, 0.05], size=m*n)
A = a.reshape((m, n))

print("A =", A)
np.save("data/A.npy", A)

b = np.random.randint(-100, 100, size=m*n) * np.random.choice([0, 1], p=[0.95, 0.05], size=m*n)
B = b.reshape((m, n))

print("\nB =", B)
np.save("data/B.npy", B)

A = [[  0 -50   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [ 83   0 -72 ...   0   0   0]]

B = [[  0   0   0 ...   0   0   0]
 [  0   0   0 ... -36   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0 -35 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [-40   0   0 ...   0   0   0]]


In [6]:
def sparse_to_coo(A, destination_path):
    m, n = A.shape
    
    rows = []
    columns = []
    values = []
    
    for i in range(m):
        for j in range(n):
            if A[i, j] > 0:
                rows.append(i)
                columns.append(j)
                values.append(A[i, j])
    coo = pd.DataFrame({
        'row': rows,
        'column': columns,
        'value': values
    })
    
    print("\nFormato COO:")
    print(coo)
    coo.to_csv(destination_path, index=False)

In [7]:
def sparse_to_csr(A, destination_path):
    m, n = A.shape

    data = []
    indices = []
    indptr = [0]

    for i in range(m):
        row_data = A[i, A[i, :] != 0]
        row_indices = np.where(A[i, :] != 0)[0]

        data.extend(row_data)
        indices.extend(row_indices)
        indptr.append(len(data))
    
    indptr.pop()
    indptr.extend([np.nan] * (len(data) - len(indptr)))

    csr = pd.DataFrame({
        'data': data,
        'indices': indices,
        'indptr': indptr
    })

    print("\nFormato CSR:")
    print(csr)
    csr.to_csv(destination_path, index=False)

In [8]:
def sparse_to_csc(A, destination_path):
    m, n = A.shape

    data = []
    indices = []
    indptr = [0]

    for j in range(n):
        column_data = A[A[:, j] != 0, j]
        column_indices = np.where(A[:, j] != 0)[0]

        data.extend(column_data)
        indices.extend(column_indices)
        indptr.append(len(data))
    
    indptr.pop()
    indptr.extend([np.nan] * (len(data) - len(indptr)))
    
    csc = pd.DataFrame({
        'data': data,
        'indices': indices,
        'indptr': indptr
    })

    print("\nFormato CSC:")
    print(csc)
    csc.to_csv(destination_path, index=False)

In [9]:
def convert_matrix(source_path, destination_path, method):
    A = np.load(source_path)
    print('Matriz Original:')
    print(A)
    
    if method == 'csr':
        sparse_to_csr(A, destination_path)
    elif method == 'csc':
        sparse_to_csc(A, destination_path)
    else:
        sparse_to_coo(A, destination_path)

### Formato COO

In [10]:
convert_matrix('data/A.npy', 'data/A_coo.csv', 'coo')

Matriz Original:
[[  0 -50   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [ 83   0 -72 ...   0   0   0]]

Formato COO:
         row  column  value
0          0      86     89
1          0     104     56
2          0     246      9
3          0     263     84
4          0     283     82
...      ...     ...    ...
242076  3499    2667     75
242077  3499    2721      8
242078  3499    2732     87
242079  3499    2784     49
242080  3499    2796     53

[242081 rows x 3 columns]


In [11]:
convert_matrix('data/B.npy', 'data/B_coo.csv', 'coo')

Matriz Original:
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ... -36   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0 -35 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [-40   0   0 ...   0   0   0]]

Formato COO:
         row  column  value
0          0      72     59
1          0      79     12
2          0     150     33
3          0     188     50
4          0     193     43
...      ...     ...    ...
242369  3499    2581     38
242370  3499    2635     13
242371  3499    2701     36
242372  3499    2763     52
242373  3499    2789     80

[242374 rows x 3 columns]


### Formato CSR

In [12]:
convert_matrix('data/A.npy', 'data/A_csr.csv', 'csr')

Matriz Original:
[[  0 -50   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [ 83   0 -72 ...   0   0   0]]

Formato CSR:
        data  indices  indptr
0        -50        1     0.0
1         -4       62   137.0
2        -22       77   260.0
3         89       86   398.0
4        -88       88   534.0
...      ...      ...     ...
486929   -13     2745     NaN
486930   -62     2753     NaN
486931   -38     2771     NaN
486932    49     2784     NaN
486933    53     2796     NaN

[486934 rows x 3 columns]


In [13]:
convert_matrix('data/B.npy', 'data/B_csr.csv', 'csr')

Matriz Original:
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ... -36   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0 -35 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [-40   0   0 ...   0   0   0]]

Formato CSR:
        data  indices  indptr
0        -99       59     0.0
1         59       72   148.0
2         12       79   291.0
3        -69       90   443.0
4        -28       96   585.0
...      ...      ...     ...
486938   -61     2651     NaN
486939   -13     2689     NaN
486940    36     2701     NaN
486941    52     2763     NaN
486942    80     2789     NaN

[486943 rows x 3 columns]


### Formato CSC

In [14]:
convert_matrix('data/A.npy', 'data/A_csc.csv', 'csc')

Matriz Original:
[[  0 -50   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [ 83   0 -72 ...   0   0   0]]

Formato CSC:
        data  indices  indptr
0         26        9     0.0
1         31       16   164.0
2         53       23   333.0
3        -84       31   495.0
4        -67       70   679.0
...      ...      ...     ...
486929    92     3366     NaN
486930    90     3377     NaN
486931    13     3415     NaN
486932   -54     3420     NaN
486933    57     3425     NaN

[486934 rows x 3 columns]


In [15]:
convert_matrix('data/B.npy', 'data/B_csc.csv', 'csc')

Matriz Original:
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ... -36   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0 -35 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [-40   0   0 ...   0   0   0]]

Formato CSC:
        data  indices  indptr
0        -97       10     0.0
1         81       34   158.0
2       -100       49   306.0
3         75      122   461.0
4        -16      143   615.0
...      ...      ...     ...
486938    -5     3416     NaN
486939    47     3430     NaN
486940    99     3459     NaN
486941   -50     3462     NaN
486942    11     3470     NaN

[486943 rows x 3 columns]


## Ejercicio 4

In [16]:
def matrix_addition_coo(A, B):
    return pd.concat([A_coo, B_coo]).groupby(['row', 'column'], as_index=False)[['value']].sum()

In [17]:
def reverse_coo(coo, shape):
    A = np.zeros(shape)
    
    for idx, row in coo.iterrows():
        A[row['row'], row['column']] = row['value']
    
    return(A)

In [18]:
A_coo = pd.read_csv('data/A_coo.csv')
B_coo = pd.read_csv('data/B_coo.csv')

In [19]:
A_B_coo = matrix_addition_coo(A_coo, B_coo)
print("Suma en formato COO:")
print(A_B_coo)
A_B = reverse_coo(A_B_coo, (m, n))
print("\nSuma en formato Disperso:")
print(A_B)

Suma en formato COO:
         row  column  value
0          0      72     59
1          0      79     12
2          0      86     89
3          0     104     56
4          0     150     33
...      ...     ...    ...
478410  3499    2732     87
478411  3499    2763     52
478412  3499    2784     49
478413  3499    2789     80
478414  3499    2796     53

[478415 rows x 3 columns]

Suma en formato Disperso:
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [83.  0.  0. ...  0.  0.  0.]]
